### ISSUE TITLE
Bug Issue

### ISSUE THREAD

**Issue by ShadowSlayer78** [Cycro54/XP-Shop#1]
[crash-2023-09-08_15.27.24-client.txt](https://github.com/Cycro54/XP-Shop/files/12566304/crash-2023-09-08_15.27.24-client.txt)
[crash-2023-09-08_15.29.52-server.txt](https://github.com/Cycro54/XP-Shop/files/12566305/crash-2023-09-08_15.29.52-server.txt)

**Comment by Cycro54** [comment]
Should be fixed in xp_shop-1.16.5-1.0.1

I was trying to modify the code and add stuff like Auto-price generation but too many things were broken.
My plan is to just rewrite it for 1.19.2
